export enum CategoriesEnum {
  EXPERIENCE = 'EXPERIENCE',
  QUALIFICATION = 'QUALIFICATION',
  SELF_SUFFICIENCY = 'SELF_SUFFICIENCY',
  STRESS_TOLERANCE = 'STRESS_TOLERANCE',
  COMMUNICABILITY = 'COMMUNICABILITY',
  CREATIVITY = 'CREATIVITY',
  RATIONALITY = 'RATIONALITY',
}
